INSERT INTO PERSONNE (Nom, Revenu, Age, Sexe) VALUES 
('Adam', 25, 1, 'M'),
('Abdoullah', 27, 21, 'M'),
('Ismail', 44, 40, 'M'),
('Omar', 11, 10, 'M'),
('Ali', 26, 30, 'M'),
('Otmane', 60, 20, 'M'),
('Driss', 79, 30, 'M'),
('Youssef', 50, 40, 'M'),
('Mohammed', 79, 30, 'M'),
('Hamza', 85, 35, 'M'),
('Houda', 79, 28, 'F'),
('Nadia', 50, 29, 'F'),
('FatimaZouhra', 41, 30, 'F'),
('Zeinab', 79, 30, 'F'),
('Ghita', 75, 87, 'F'),
('Hiba', 55, 42, 'F'),
('Kenza', 30, 41, 'F');

INSERT INTO PARENTS (Fils, Parent) VALUES
('Adam', 'Otmane'),
('Adam', 'Hiba'),
('Abdoullah', 'Otmane'),
('Abdoullah', 'Hiba'),
('Ismail', 'Zeinab'),
('Ismail', 'Driss'),
('Omar', 'FatimaZouhra'),
('Omar', 'Ismail'),
('Ali', 'Nadia'),
('Ali', 'Youssef'),
('Otmane', 'Hamza'),
('Youssef', 'Ghita'),
('FatimaZouhra', 'Houda'),
('FatimaZouhra', 'Mohammed'),
('Hiba', 'Ghita'),
('Kenza', 'Nadia'),
('Kenza', 'Youssef');
