CREATE TABLE DELIVERERS (
    DELIVERERID INT NOT NULL PRIMARY KEY,
    nom VARCHAR(20) NOT NULL,
    prenom VARCHAR(20) NOT NULL,
    annee_de_naissance INT NOT NULL,
    sexe CHAR(1) NOT NULL CHECK (sexe IN ('M','F')),
    annee_embauche INT,
    rue VARCHAR(20) NOT NULL,
    numero_maison INT NOT NULL,
    ville VARCHAR(20) NOT NULL,
    code_postal VARCHAR(20) NOT NULL,
    numero_tele VARCHAR(15) NOT NULL,
    numero_tele_bureau VARCHAR(15)
);

CREATE TABLE COMPANIES (
    CompanyID INT NOT NULL PRIMARY KEY,
    MANDAT VARCHAR(10) NOT NULL,
    DELIVERERID INT,
    CONSTRAINT fk_deliverer FOREIGN KEY (DELIVERERID) REFERENCES DELIVERERS (DELIVERERID)
);

CREATE TABLE COMPANYDEL (
    DELIVERERID INT NOT NULL,
    CompanyID INT NOT NULL,
    NUMDELIVERIES INT NOT NULL,
    NUMCOLLECTIONS INT NOT NULL,
    CONSTRAINT C_Deliver PRIMARY KEY (DELIVERERID, CompanyID),
    CONSTRAINT CD_Deliver CHECK (NUMDELIVERIES > 0 OR NUMCOLLECTIONS > 0),
    CONSTRAINT fk_deliverer1 FOREIGN KEY (DELIVERERID) REFERENCES DELIVERERS (DELIVERERID),
    CONSTRAINT fk_company FOREIGN KEY (CompanyID) REFERENCES COMPANIES (CompanyID) 
);

CREATE TABLE PENALITES (
    PENALTYID INT NOT NULL PRIMARY KEY,
    date_amende DATE NOT NULL,
    montant INT NOT NULL,
    DELIVERERID INT,
    CONSTRAINT fk_deliverer2 FOREIGN KEY (DELIVERERID) REFERENCES DELIVERERS (DELIVERERID)
);
